
//Do not change this file.
var cal_grant_transfer_entitlement_verification_cal_grant_transfer_entitlement_verification = window.cal_grant_transfer_entitlement_verification_cal_grant_transfer_entitlement_verification = window.cal_grant_transfer_entitlement_verification_cal_grant_transfer_entitlement_verification || {};
