
//Do not change this file.
var verification_of_independent_status_verification_of_independent_status___ward = window.verification_of_independent_status_verification_of_independent_status___ward = window.verification_of_independent_status_verification_of_independent_status___ward || {};
